<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="aboutdialog.ui" line="14"/>
        <source>About</source>
        <translation>About</translation>
    </message>
    <message>
        <location filename="aboutdialog.ui" line="33"/>
        <source>TextLabel</source>
        <translation> </translation>
    </message>
    <message>
        <location filename="aboutdialog.cpp" line="32"/>
        <source>error while reading</source>
        <translation>error while reading</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="mainwindow.ui" line="20"/>
        <source>MainWindow</source>
        <translation>MainWindow</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="81"/>
        <source>&amp;Help</source>
        <translation>&amp;Help</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="94"/>
        <source>&amp;Close</source>
        <translation>&amp;Close</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="113"/>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <source>New</source>
        <translation type="vanished">New</translation>
    </message>
    <message>
        <source>Open</source>
        <translation type="vanished">Open</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="147"/>
        <source>Open (read only)</source>
        <translation>Open (read only)</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="vanished">Save</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation type="vanished">Exit</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="124"/>
        <source>Options</source>
        <translation>Options</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="137"/>
        <source>&amp;New</source>
        <translation>&amp;New</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="142"/>
        <source>&amp;Open</source>
        <translation>&amp;Open</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="152"/>
        <source>&amp;Save</source>
        <translation>&amp;Save</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="157"/>
        <source>&amp;Exit</source>
        <translation>&amp;Exit</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="162"/>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="167"/>
        <source>English</source>
        <translation>English</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="172"/>
        <source>Russian</source>
        <translation>Russian</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="vanished">Close</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="67"/>
        <location filename="mainwindow.cpp" line="139"/>
        <location filename="mainwindow.cpp" line="164"/>
        <source>The current changes will be lost, continue?
</source>
        <translation>The current changes will be lost, continue?\n</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="85"/>
        <location filename="mainwindow.cpp" line="95"/>
        <location filename="mainwindow.cpp" line="119"/>
        <source>Error</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="85"/>
        <source>Unable to open file for writing!</source>
        <translation>Unable to open file for writing!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="95"/>
        <source>Error writing file: %1</source>
        <translation>Error writing file: %1</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="112"/>
        <source>Open file</source>
        <translation>Open file</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="112"/>
        <location filename="mainwindow.cpp" line="184"/>
        <source>Text files (*.txt);;All files (*.*)</source>
        <translation>Text files (*.txt);;All files (*.*)</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="119"/>
        <source>Unable to open file for reading!</source>
        <translation>Unable to open file for reading!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="184"/>
        <source>Save file</source>
        <translation>Save file</translation>
    </message>
</context>
</TS>
